// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_bMqip7Eqy565oEhwjeCBlt8g-vsTjyM',
    appId: '1:135599988085:web:c953193d3b84ced7e8473c',
    messagingSenderId: '135599988085',
    projectId: 'quiztale-a678a',
    authDomain: 'quiztale-a678a.firebaseapp.com',
    storageBucket: 'quiztale-a678a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHZ-etAXUTy-APEiHHHqv15Eg1xb-qZo0',
    appId: '1:135599988085:android:9190577e08a194cee8473c',
    messagingSenderId: '135599988085',
    projectId: 'quiztale-a678a',
    storageBucket: 'quiztale-a678a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF5r7i_1Zjnv7nYmvtu619ZWnJMAGFAjQ',
    appId: '1:135599988085:ios:4d622aefbd5a7eabe8473c',
    messagingSenderId: '135599988085',
    projectId: 'quiztale-a678a',
    storageBucket: 'quiztale-a678a.firebasestorage.app',
    iosBundleId: 'com.example.quiztale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF5r7i_1Zjnv7nYmvtu619ZWnJMAGFAjQ',
    appId: '1:135599988085:ios:4d622aefbd5a7eabe8473c',
    messagingSenderId: '135599988085',
    projectId: 'quiztale-a678a',
    storageBucket: 'quiztale-a678a.firebasestorage.app',
    iosBundleId: 'com.example.quiztale',
  );
}
